2019-07-22 21:46:49,837 - base.py:[28] - [INFO] - _open is accessing address http:192.168.0.91 at line[46]
2019-07-22 21:46:49,838 - base.py:[32] - [INFO] - http:192.168.0.91 loading successed!
2019-07-22 21:46:49,874 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000023E3E923828> had already find the element ('xpath', "//*[@id='user']")
2019-07-22 21:46:49,934 - base.py:[64] - [INFO] - inputValue:[('xpath', "//*[@id='user']")] is receiveing value [admin]
2019-07-22 21:46:49,955 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000023E3E923828> had already find the element ('xpath', "//*[@id='password']")
2019-07-22 21:46:50,022 - base.py:[64] - [INFO] - inputValue:[('xpath', "//*[@id='password']")] is receiveing value [admin2003]
2019-07-22 21:46:50,044 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000023E3E923828> had already find the element ('xpath', "//*[@id='submit']")
2019-07-22 21:46:54,292 - base.py:[42] - [INFO] - The page of test_01previewPNGfiles (g_preview_sta.PreviewTest) had already find the element ('xpath', "//*[@id='fileList']/tr[3]/td[2]/a/span[1]")
2019-07-22 21:47:30,233 - base.py:[28] - [INFO] - _open is accessing address http:192.168.0.91 at line[46]
2019-07-22 21:47:30,233 - base.py:[32] - [INFO] - http:192.168.0.91 loading successed!
2019-07-22 21:47:40,756 - base.py:[39] - [ERROR] - finding element timeout!, details
Traceback (most recent call last):
  File "E:\Security_retail_test_project\retail\test_case\page_obj\base.py", line 37, in findElement
    WebDriverWait(self.driver, 10).until(EC.visibility_of_element_located(loc))
  File "C:\Python36\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2019-07-22 21:47:46,759 - base.py:[28] - [INFO] - _open is accessing address http:192.168.0.91 at line[46]
2019-07-22 21:47:46,759 - base.py:[32] - [INFO] - http:192.168.0.91 loading successed!
2019-07-22 21:47:46,784 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000023E3E94DB38> had already find the element ('xpath', "//*[@id='user']")
2019-07-22 21:47:46,849 - base.py:[64] - [INFO] - inputValue:[('xpath', "//*[@id='user']")] is receiveing value [admin]
2019-07-22 21:47:46,871 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000023E3E94DB38> had already find the element ('xpath', "//*[@id='password']")
2019-07-22 21:47:46,933 - base.py:[64] - [INFO] - inputValue:[('xpath', "//*[@id='password']")] is receiveing value [admin2003]
2019-07-22 21:47:46,954 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000023E3E94DB38> had already find the element ('xpath', "//*[@id='submit']")
2019-07-22 21:47:49,199 - base.py:[42] - [INFO] - The page of test_01searchfiles (h_search_sta.SearchTest) had already find the element ('xpath', "//*[@id='searchbox']")
2019-07-22 21:47:49,763 - base.py:[42] - [INFO] - The page of test_01searchfiles (h_search_sta.SearchTest) had already find the element ('xpath', "//*[@id='searchbox']")
2019-07-22 21:47:52,129 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000023E3E94DB38> had already find the element ('xpath', "//*[@id='expand']")
2019-07-22 21:47:54,203 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000023E3E94DB38> had already find the element ('xpath', "//*[@id='expanddiv']/ul/li[2]/a")
2019-07-22 21:47:57,640 - base.py:[28] - [INFO] - _open is accessing address http:192.168.0.91 at line[46]
2019-07-22 21:47:57,640 - base.py:[32] - [INFO] - http:192.168.0.91 loading successed!
2019-07-22 21:47:57,659 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000023E3E911358> had already find the element ('xpath', "//*[@id='user']")
2019-07-22 21:47:57,713 - base.py:[64] - [INFO] - inputValue:[('xpath', "//*[@id='user']")] is receiveing value [admin]
2019-07-22 21:47:57,730 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000023E3E911358> had already find the element ('xpath', "//*[@id='password']")
2019-07-22 21:47:57,802 - base.py:[64] - [INFO] - inputValue:[('xpath', "//*[@id='password']")] is receiveing value [admin2003]
2019-07-22 21:47:57,818 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000023E3E911358> had already find the element ('xpath', "//*[@id='submit']")
2019-07-22 21:47:59,445 - base.py:[42] - [INFO] - The page of test_02searchfolder (h_search_sta.SearchTest) had already find the element ('xpath', "//*[@id='searchbox']")
2019-07-22 21:48:00,038 - base.py:[42] - [INFO] - The page of test_02searchfolder (h_search_sta.SearchTest) had already find the element ('xpath', "//*[@id='searchbox']")
2019-07-22 21:48:03,386 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000023E3E911358> had already find the element ('xpath', "//*[@id='expand']")
2019-07-22 21:48:05,458 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000023E3E911358> had already find the element ('xpath', "//*[@id='expanddiv']/ul/li[2]/a")
2019-07-22 21:48:11,603 - base.py:[28] - [INFO] - _open is accessing address http:192.168.0.91 at line[46]
2019-07-22 21:48:11,603 - base.py:[32] - [INFO] - http:192.168.0.91 loading successed!
2019-07-22 21:48:11,628 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000023E3E94DA90> had already find the element ('xpath', "//*[@id='user']")
2019-07-22 21:48:11,690 - base.py:[64] - [INFO] - inputValue:[('xpath', "//*[@id='user']")] is receiveing value [admin]
2019-07-22 21:48:11,710 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000023E3E94DA90> had already find the element ('xpath', "//*[@id='password']")
2019-07-22 21:48:11,776 - base.py:[64] - [INFO] - inputValue:[('xpath', "//*[@id='password']")] is receiveing value [admin2003]
2019-07-22 21:48:11,797 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000023E3E94DA90> had already find the element ('xpath', "//*[@id='submit']")
2019-07-22 21:48:13,164 - base.py:[42] - [INFO] - The page of test_01shareuser (i_share_sta.ShareTest) had already find the element ('xpath', '/html/body/div[3]/div/div[2]/div[3]/table/tbody/tr[4]/td[1]/label')
2019-07-22 21:48:13,282 - base.py:[42] - [INFO] - The page of test_01shareuser (i_share_sta.ShareTest) had already find the element ('xpath', '/html/body/div[3]/div/div[2]/div[3]/div[1]/div[1]/div[4]')
2019-07-22 21:48:44,513 - base.py:[39] - [ERROR] - finding element timeout!, details
Traceback (most recent call last):
  File "E:\Security_retail_test_project\retail\test_case\page_obj\base.py", line 37, in findElement
    WebDriverWait(self.driver, 10).until(EC.visibility_of_element_located(loc))
  File "C:\Python36\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2019-07-22 21:48:45,331 - base.py:[28] - [INFO] - _open is accessing address http:192.168.0.91 at line[46]
2019-07-22 21:48:45,331 - base.py:[32] - [INFO] - http:192.168.0.91 loading successed!
2019-07-22 21:48:55,853 - base.py:[39] - [ERROR] - finding element timeout!, details
Traceback (most recent call last):
  File "E:\Security_retail_test_project\retail\test_case\page_obj\base.py", line 37, in findElement
    WebDriverWait(self.driver, 10).until(EC.visibility_of_element_located(loc))
  File "C:\Python36\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2019-07-22 21:48:56,653 - base.py:[28] - [INFO] - _open is accessing address http:192.168.0.91 at line[46]
2019-07-22 21:48:56,653 - base.py:[32] - [INFO] - http:192.168.0.91 loading successed!
2019-07-22 21:49:07,193 - base.py:[39] - [ERROR] - finding element timeout!, details
Traceback (most recent call last):
  File "E:\Security_retail_test_project\retail\test_case\page_obj\base.py", line 37, in findElement
    WebDriverWait(self.driver, 10).until(EC.visibility_of_element_located(loc))
  File "C:\Python36\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2019-07-22 21:49:07,992 - base.py:[28] - [INFO] - _open is accessing address http:192.168.0.91 at line[46]
2019-07-22 21:49:07,992 - base.py:[32] - [INFO] - http:192.168.0.91 loading successed!
2019-07-22 21:49:18,548 - base.py:[39] - [ERROR] - finding element timeout!, details
Traceback (most recent call last):
  File "E:\Security_retail_test_project\retail\test_case\page_obj\base.py", line 37, in findElement
    WebDriverWait(self.driver, 10).until(EC.visibility_of_element_located(loc))
  File "C:\Python36\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2019-07-22 21:49:19,280 - base.py:[28] - [INFO] - _open is accessing address http:192.168.0.91 at line[46]
2019-07-22 21:49:19,280 - base.py:[32] - [INFO] - http:192.168.0.91 loading successed!
2019-07-22 21:49:29,803 - base.py:[39] - [ERROR] - finding element timeout!, details
Traceback (most recent call last):
  File "E:\Security_retail_test_project\retail\test_case\page_obj\base.py", line 37, in findElement
    WebDriverWait(self.driver, 10).until(EC.visibility_of_element_located(loc))
  File "C:\Python36\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2019-07-22 21:49:30,541 - base.py:[28] - [INFO] - _open is accessing address http:192.168.0.91 at line[46]
2019-07-22 21:49:30,541 - base.py:[32] - [INFO] - http:192.168.0.91 loading successed!
2019-07-22 21:49:41,085 - base.py:[39] - [ERROR] - finding element timeout!, details
Traceback (most recent call last):
  File "E:\Security_retail_test_project\retail\test_case\page_obj\base.py", line 37, in findElement
    WebDriverWait(self.driver, 10).until(EC.visibility_of_element_located(loc))
  File "C:\Python36\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2019-07-22 21:49:47,068 - base.py:[28] - [INFO] - _open is accessing address http:192.168.0.91 at line[46]
2019-07-22 21:49:47,068 - base.py:[32] - [INFO] - http:192.168.0.91 loading successed!
2019-07-22 21:49:47,092 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000023E3E982160> had already find the element ('xpath', "//*[@id='user']")
2019-07-22 21:49:47,157 - base.py:[64] - [INFO] - inputValue:[('xpath', "//*[@id='user']")] is receiveing value [admin]
2019-07-22 21:49:47,178 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000023E3E982160> had already find the element ('xpath', "//*[@id='password']")
2019-07-22 21:49:47,242 - base.py:[64] - [INFO] - inputValue:[('xpath', "//*[@id='password']")] is receiveing value [admin2003]
2019-07-22 21:49:47,262 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000023E3E982160> had already find the element ('xpath', "//*[@id='submit']")
2019-07-22 21:49:48,538 - base.py:[42] - [INFO] - The page of test_01copyfiles (j_copy_sta.CopyTest) had already find the element ('xpath', "//*[@id='fileList']/tr[4]/td[1]/label")
2019-07-22 21:49:48,657 - base.py:[42] - [INFO] - The page of test_01copyfiles (j_copy_sta.CopyTest) had already find the element ('xpath', "//*[@id='selectedActionsList']/a[3]")
2019-07-22 21:49:49,257 - base.py:[42] - [INFO] - The page of test_01copyfiles (j_copy_sta.CopyTest) had already find the element ('xpath', "//*[@id='body-user']/div[8]/div[2]/button[1]")
2019-07-22 21:49:50,621 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000023E3E982160> had already find the element ('xpath', "//*[@id='expand']")
2019-07-22 21:49:52,695 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000023E3E982160> had already find the element ('xpath', "//*[@id='expanddiv']/ul/li[2]/a")
2019-07-22 21:50:02,268 - base.py:[28] - [INFO] - _open is accessing address http:192.168.0.91 at line[46]
2019-07-22 21:50:02,268 - base.py:[32] - [INFO] - http:192.168.0.91 loading successed!
2019-07-22 21:50:02,292 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000023E3E94DCC0> had already find the element ('xpath', "//*[@id='user']")
2019-07-22 21:50:02,355 - base.py:[64] - [INFO] - inputValue:[('xpath', "//*[@id='user']")] is receiveing value [admin]
2019-07-22 21:50:02,376 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000023E3E94DCC0> had already find the element ('xpath', "//*[@id='password']")
2019-07-22 21:50:02,442 - base.py:[64] - [INFO] - inputValue:[('xpath', "//*[@id='password']")] is receiveing value [admin2003]
2019-07-22 21:50:02,463 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000023E3E94DCC0> had already find the element ('xpath', "//*[@id='submit']")
2019-07-22 21:50:03,774 - base.py:[42] - [INFO] - The page of test_01movefileslocal (k_move_sta.MoverTest) had already find the element ('xpath', '/html/body/div[3]/div/div[2]/div[3]/table/tbody/tr[4]/td[1]/label')
2019-07-22 21:50:03,889 - base.py:[42] - [INFO] - The page of test_01movefileslocal (k_move_sta.MoverTest) had already find the element ('xpath', '/html/body/div[3]/div/div[2]/div[3]/table/thead/tr/th[2]/div/span/a[3]')
2019-07-22 21:50:04,500 - base.py:[42] - [INFO] - The page of test_01movefileslocal (k_move_sta.MoverTest) had already find the element ('xpath', "//*[@id='body-user']/div[8]/div[2]/button[2]")
2019-07-22 21:50:05,087 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000023E3E94DCC0> had already find the element ('xpath', "//*[@id='expand']")
2019-07-22 21:50:07,165 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000023E3E94DCC0> had already find the element ('xpath', "//*[@id='expanddiv']/ul/li[2]/a")
2019-07-22 21:52:08,635 - base.py:[28] - [INFO] - _open is accessing address http:192.168.0.91 at line[46]
2019-07-22 21:52:08,635 - base.py:[32] - [INFO] - http:192.168.0.91 loading successed!
2019-07-22 21:52:08,661 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000023E3E99B518> had already find the element ('xpath', "//*[@id='user']")
2019-07-22 21:52:08,726 - base.py:[64] - [INFO] - inputValue:[('xpath', "//*[@id='user']")] is receiveing value [admin]
2019-07-22 21:52:08,747 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000023E3E99B518> had already find the element ('xpath', "//*[@id='password']")
2019-07-22 21:52:08,809 - base.py:[64] - [INFO] - inputValue:[('xpath', "//*[@id='password']")] is receiveing value [admin2003]
2019-07-22 21:52:08,830 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000023E3E99B518> had already find the element ('xpath', "//*[@id='submit']")
2019-07-22 21:52:12,720 - base.py:[42] - [INFO] - The page of test_01renamefiles (n_rename_sta.RenameTest) had already find the element ('xpath', '/html/body/div[3]/div/div[2]/div[3]/table/tbody/tr[4]/td[1]/label')
2019-07-22 21:52:12,833 - base.py:[42] - [INFO] - The page of test_01renamefiles (n_rename_sta.RenameTest) had already find the element ('xpath', '/html/body/div[3]/div/div[2]/div[3]/table/thead/tr/th[2]/div/span/a[1]')
2019-07-22 21:52:13,917 - base.py:[42] - [INFO] - The page of test_01renamefiles (n_rename_sta.RenameTest) had already find the element ('xpath', "//*[@id='fileList']/tr[4]/td[2]/form/input")
2019-07-22 21:52:15,334 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000023E3E99B518> had already find the element ('xpath', "//*[@id='expand']")
2019-07-22 21:52:17,447 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000023E3E99B518> had already find the element ('xpath', "//*[@id='expanddiv']/ul/li[2]/a")
2019-07-22 21:52:20,889 - base.py:[28] - [INFO] - _open is accessing address http:192.168.0.91 at line[46]
2019-07-22 21:52:20,890 - base.py:[32] - [INFO] - http:192.168.0.91 loading successed!
2019-07-22 21:52:20,911 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000023E3E98BE10> had already find the element ('xpath', "//*[@id='user']")
2019-07-22 21:52:20,971 - base.py:[64] - [INFO] - inputValue:[('xpath', "//*[@id='user']")] is receiveing value [admin]
2019-07-22 21:52:20,989 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000023E3E98BE10> had already find the element ('xpath', "//*[@id='password']")
2019-07-22 21:52:21,055 - base.py:[64] - [INFO] - inputValue:[('xpath', "//*[@id='password']")] is receiveing value [admin2003]
2019-07-22 21:52:21,072 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000023E3E98BE10> had already find the element ('xpath', "//*[@id='submit']")
2019-07-22 21:52:21,919 - base.py:[42] - [INFO] - The page of test_02renamefolders (n_rename_sta.RenameTest) had already find the element ('xpath', '/html/body/div[3]/div/div[2]/div[3]/table/tbody/tr[2]/td[1]/label')
2019-07-22 21:52:23,033 - base.py:[42] - [INFO] - The page of test_02renamefolders (n_rename_sta.RenameTest) had already find the element ('xpath', '/html/body/div[3]/div/div[2]/div[3]/table/thead/tr/th[2]/div/span/a[1]')
2019-07-22 21:52:24,159 - base.py:[42] - [INFO] - The page of test_02renamefolders (n_rename_sta.RenameTest) had already find the element ('xpath', "//*[@id='fileList']/tr[2]/td[2]/form/input")
2019-07-22 21:52:25,500 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000023E3E98BE10> had already find the element ('xpath', "//*[@id='expand']")
2019-07-22 21:52:27,595 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000023E3E98BE10> had already find the element ('xpath', "//*[@id='expanddiv']/ul/li[2]/a")
