2019-07-29 21:47:15,539 - base.py:[28] - [INFO] - _open is accessing address http:192.168.0.91 at line[46]
2019-07-29 21:47:15,539 - base.py:[32] - [INFO] - http:192.168.0.91 loading successed!
2019-07-29 21:47:15,565 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000013F350749B0> had already find the element ('xpath', "//*[@id='user']")
2019-07-29 21:47:15,633 - base.py:[64] - [INFO] - inputValue:[('xpath', "//*[@id='user']")] is receiveing value [admin]
2019-07-29 21:47:15,655 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000013F350749B0> had already find the element ('xpath', "//*[@id='password']")
2019-07-29 21:47:15,726 - base.py:[64] - [INFO] - inputValue:[('xpath', "//*[@id='password']")] is receiveing value [admin2003]
2019-07-29 21:47:15,750 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000013F350749B0> had already find the element ('xpath', "//*[@id='submit']")
2019-07-29 21:47:20,573 - base.py:[42] - [INFO] - The page of test_01previewPNGfiles (g_preview_sta.PreviewTest) had already find the element ('xpath', "//*[@id='fileList']/tr[3]/td[2]/a/span[1]")
2019-07-29 21:47:56,887 - base.py:[28] - [INFO] - _open is accessing address http:192.168.0.91 at line[46]
2019-07-29 21:47:56,887 - base.py:[32] - [INFO] - http:192.168.0.91 loading successed!
2019-07-29 21:48:07,438 - base.py:[39] - [ERROR] - finding element timeout!, details
Traceback (most recent call last):
  File "E:\Security_retail_test_project\retail\test_case\page_obj\base.py", line 37, in findElement
    WebDriverWait(self.driver, 10).until(EC.visibility_of_element_located(loc))
  File "C:\Python36\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2019-07-29 21:48:13,209 - base.py:[28] - [INFO] - _open is accessing address http:192.168.0.91 at line[46]
2019-07-29 21:48:13,209 - base.py:[32] - [INFO] - http:192.168.0.91 loading successed!
2019-07-29 21:48:13,234 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000013F3509D9B0> had already find the element ('xpath', "//*[@id='user']")
2019-07-29 21:48:13,297 - base.py:[64] - [INFO] - inputValue:[('xpath', "//*[@id='user']")] is receiveing value [admin]
2019-07-29 21:48:13,319 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000013F3509D9B0> had already find the element ('xpath', "//*[@id='password']")
2019-07-29 21:48:13,384 - base.py:[64] - [INFO] - inputValue:[('xpath', "//*[@id='password']")] is receiveing value [admin2003]
2019-07-29 21:48:13,405 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000013F3509D9B0> had already find the element ('xpath', "//*[@id='submit']")
2019-07-29 21:48:16,480 - base.py:[42] - [INFO] - The page of test_01searchfiles (h_search_sta.SearchTest) had already find the element ('xpath', "//*[@id='searchbox']")
2019-07-29 21:48:17,043 - base.py:[42] - [INFO] - The page of test_01searchfiles (h_search_sta.SearchTest) had already find the element ('xpath', "//*[@id='searchbox']")
2019-07-29 21:48:19,449 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000013F3509D9B0> had already find the element ('xpath', "//*[@id='expand']")
2019-07-29 21:48:21,528 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000013F3509D9B0> had already find the element ('xpath', "//*[@id='expanddiv']/ul/li[2]/a")
2019-07-29 21:48:24,993 - base.py:[28] - [INFO] - _open is accessing address http:192.168.0.91 at line[46]
2019-07-29 21:48:24,993 - base.py:[32] - [INFO] - http:192.168.0.91 loading successed!
2019-07-29 21:48:25,018 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000013F3507AEB8> had already find the element ('xpath', "//*[@id='user']")
2019-07-29 21:48:25,078 - base.py:[64] - [INFO] - inputValue:[('xpath', "//*[@id='user']")] is receiveing value [admin]
2019-07-29 21:48:25,096 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000013F3507AEB8> had already find the element ('xpath', "//*[@id='password']")
2019-07-29 21:48:25,162 - base.py:[64] - [INFO] - inputValue:[('xpath', "//*[@id='password']")] is receiveing value [admin2003]
2019-07-29 21:48:25,179 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000013F3507AEB8> had already find the element ('xpath', "//*[@id='submit']")
2019-07-29 21:48:26,974 - base.py:[42] - [INFO] - The page of test_02searchfolder (h_search_sta.SearchTest) had already find the element ('xpath', "//*[@id='searchbox']")
2019-07-29 21:48:27,560 - base.py:[42] - [INFO] - The page of test_02searchfolder (h_search_sta.SearchTest) had already find the element ('xpath', "//*[@id='searchbox']")
2019-07-29 21:48:30,944 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000013F3507AEB8> had already find the element ('xpath', "//*[@id='expand']")
2019-07-29 21:48:33,043 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000013F3507AEB8> had already find the element ('xpath', "//*[@id='expanddiv']/ul/li[2]/a")
2019-07-29 21:48:39,465 - base.py:[28] - [INFO] - _open is accessing address http:192.168.0.91 at line[46]
2019-07-29 21:48:39,466 - base.py:[32] - [INFO] - http:192.168.0.91 loading successed!
2019-07-29 21:48:39,492 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000013F3509DA90> had already find the element ('xpath', "//*[@id='user']")
2019-07-29 21:48:39,556 - base.py:[64] - [INFO] - inputValue:[('xpath', "//*[@id='user']")] is receiveing value [admin]
2019-07-29 21:48:39,577 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000013F3509DA90> had already find the element ('xpath', "//*[@id='password']")
2019-07-29 21:48:39,642 - base.py:[64] - [INFO] - inputValue:[('xpath', "//*[@id='password']")] is receiveing value [admin2003]
2019-07-29 21:48:39,664 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000013F3509DA90> had already find the element ('xpath', "//*[@id='submit']")
2019-07-29 21:48:41,775 - base.py:[42] - [INFO] - The page of test_01shareuser (i_share_sta.ShareTest) had already find the element ('xpath', '/html/body/div[3]/div/div[2]/div[3]/table/tbody/tr[4]/td[1]/label')
2019-07-29 21:48:41,875 - base.py:[42] - [INFO] - The page of test_01shareuser (i_share_sta.ShareTest) had already find the element ('xpath', '/html/body/div[3]/div/div[2]/div[3]/div[1]/div[1]/div[4]')
2019-07-29 21:49:13,142 - base.py:[39] - [ERROR] - finding element timeout!, details
Traceback (most recent call last):
  File "E:\Security_retail_test_project\retail\test_case\page_obj\base.py", line 37, in findElement
    WebDriverWait(self.driver, 10).until(EC.visibility_of_element_located(loc))
  File "C:\Python36\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2019-07-29 21:49:14,322 - base.py:[28] - [INFO] - _open is accessing address http:192.168.0.91 at line[46]
2019-07-29 21:49:14,322 - base.py:[32] - [INFO] - http:192.168.0.91 loading successed!
2019-07-29 21:49:24,863 - base.py:[39] - [ERROR] - finding element timeout!, details
Traceback (most recent call last):
  File "E:\Security_retail_test_project\retail\test_case\page_obj\base.py", line 37, in findElement
    WebDriverWait(self.driver, 10).until(EC.visibility_of_element_located(loc))
  File "C:\Python36\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2019-07-29 21:49:25,987 - base.py:[28] - [INFO] - _open is accessing address http:192.168.0.91 at line[46]
2019-07-29 21:49:25,987 - base.py:[32] - [INFO] - http:192.168.0.91 loading successed!
2019-07-29 21:49:36,548 - base.py:[39] - [ERROR] - finding element timeout!, details
Traceback (most recent call last):
  File "E:\Security_retail_test_project\retail\test_case\page_obj\base.py", line 37, in findElement
    WebDriverWait(self.driver, 10).until(EC.visibility_of_element_located(loc))
  File "C:\Python36\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2019-07-29 21:49:37,659 - base.py:[28] - [INFO] - _open is accessing address http:192.168.0.91 at line[46]
2019-07-29 21:49:37,659 - base.py:[32] - [INFO] - http:192.168.0.91 loading successed!
2019-07-29 21:49:48,165 - base.py:[39] - [ERROR] - finding element timeout!, details
Traceback (most recent call last):
  File "E:\Security_retail_test_project\retail\test_case\page_obj\base.py", line 37, in findElement
    WebDriverWait(self.driver, 10).until(EC.visibility_of_element_located(loc))
  File "C:\Python36\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2019-07-29 21:49:49,270 - base.py:[28] - [INFO] - _open is accessing address http:192.168.0.91 at line[46]
2019-07-29 21:49:49,270 - base.py:[32] - [INFO] - http:192.168.0.91 loading successed!
2019-07-29 21:49:59,821 - base.py:[39] - [ERROR] - finding element timeout!, details
Traceback (most recent call last):
  File "E:\Security_retail_test_project\retail\test_case\page_obj\base.py", line 37, in findElement
    WebDriverWait(self.driver, 10).until(EC.visibility_of_element_located(loc))
  File "C:\Python36\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2019-07-29 21:50:01,140 - base.py:[28] - [INFO] - _open is accessing address http:192.168.0.91 at line[46]
2019-07-29 21:50:01,141 - base.py:[32] - [INFO] - http:192.168.0.91 loading successed!
2019-07-29 21:50:11,701 - base.py:[39] - [ERROR] - finding element timeout!, details
Traceback (most recent call last):
  File "E:\Security_retail_test_project\retail\test_case\page_obj\base.py", line 37, in findElement
    WebDriverWait(self.driver, 10).until(EC.visibility_of_element_located(loc))
  File "C:\Python36\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2019-07-29 21:50:17,692 - base.py:[28] - [INFO] - _open is accessing address http:192.168.0.91 at line[46]
2019-07-29 21:50:17,692 - base.py:[32] - [INFO] - http:192.168.0.91 loading successed!
2019-07-29 21:50:17,720 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000013F3509D860> had already find the element ('xpath', "//*[@id='user']")
2019-07-29 21:50:17,782 - base.py:[64] - [INFO] - inputValue:[('xpath', "//*[@id='user']")] is receiveing value [admin]
2019-07-29 21:50:17,804 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000013F3509D860> had already find the element ('xpath', "//*[@id='password']")
2019-07-29 21:50:17,871 - base.py:[64] - [INFO] - inputValue:[('xpath', "//*[@id='password']")] is receiveing value [admin2003]
2019-07-29 21:50:17,893 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000013F3509D860> had already find the element ('xpath', "//*[@id='submit']")
2019-07-29 21:50:19,976 - base.py:[42] - [INFO] - The page of test_01copyfiles (j_copy_sta.CopyTest) had already find the element ('xpath', "//*[@id='fileList']/tr[4]/td[1]/label")
2019-07-29 21:50:20,075 - base.py:[42] - [INFO] - The page of test_01copyfiles (j_copy_sta.CopyTest) had already find the element ('xpath', "//*[@id='selectedActionsList']/a[3]")
2019-07-29 21:50:20,652 - base.py:[42] - [INFO] - The page of test_01copyfiles (j_copy_sta.CopyTest) had already find the element ('xpath', "//*[@id='body-user']/div[8]/div[2]/button[1]")
2019-07-29 21:50:22,014 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000013F3509D860> had already find the element ('xpath', "//*[@id='expand']")
2019-07-29 21:50:24,085 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000013F3509D860> had already find the element ('xpath', "//*[@id='expanddiv']/ul/li[2]/a")
2019-07-29 21:50:32,982 - base.py:[28] - [INFO] - _open is accessing address http:192.168.0.91 at line[46]
2019-07-29 21:50:32,983 - base.py:[32] - [INFO] - http:192.168.0.91 loading successed!
2019-07-29 21:50:33,012 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000013F350D3048> had already find the element ('xpath', "//*[@id='user']")
2019-07-29 21:50:33,074 - base.py:[64] - [INFO] - inputValue:[('xpath', "//*[@id='user']")] is receiveing value [admin]
2019-07-29 21:50:33,095 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000013F350D3048> had already find the element ('xpath', "//*[@id='password']")
2019-07-29 21:50:33,159 - base.py:[64] - [INFO] - inputValue:[('xpath', "//*[@id='password']")] is receiveing value [admin2003]
2019-07-29 21:50:33,180 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000013F350D3048> had already find the element ('xpath', "//*[@id='submit']")
2019-07-29 21:50:35,190 - base.py:[42] - [INFO] - The page of test_01movefileslocal (k_move_sta.MoverTest) had already find the element ('xpath', '/html/body/div[3]/div/div[2]/div[3]/table/tbody/tr[4]/td[1]/label')
2019-07-29 21:50:35,312 - base.py:[42] - [INFO] - The page of test_01movefileslocal (k_move_sta.MoverTest) had already find the element ('xpath', '/html/body/div[3]/div/div[2]/div[3]/table/thead/tr/th[2]/div/span/a[3]')
2019-07-29 21:50:35,902 - base.py:[42] - [INFO] - The page of test_01movefileslocal (k_move_sta.MoverTest) had already find the element ('xpath', "//*[@id='body-user']/div[8]/div[2]/button[2]")
2019-07-29 21:50:36,363 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000013F350D3048> had already find the element ('xpath', "//*[@id='expand']")
2019-07-29 21:50:38,448 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000013F350D3048> had already find the element ('xpath', "//*[@id='expanddiv']/ul/li[2]/a")
2019-07-29 21:52:41,903 - base.py:[28] - [INFO] - _open is accessing address http:192.168.0.91 at line[46]
2019-07-29 21:52:41,904 - base.py:[32] - [INFO] - http:192.168.0.91 loading successed!
2019-07-29 21:52:41,929 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000013F350EA5C0> had already find the element ('xpath', "//*[@id='user']")
2019-07-29 21:52:41,992 - base.py:[64] - [INFO] - inputValue:[('xpath', "//*[@id='user']")] is receiveing value [admin]
2019-07-29 21:52:42,014 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000013F350EA5C0> had already find the element ('xpath', "//*[@id='password']")
2019-07-29 21:52:42,079 - base.py:[64] - [INFO] - inputValue:[('xpath', "//*[@id='password']")] is receiveing value [admin2003]
2019-07-29 21:52:42,100 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000013F350EA5C0> had already find the element ('xpath', "//*[@id='submit']")
2019-07-29 21:52:46,236 - base.py:[42] - [INFO] - The page of test_01renamefiles (n_rename_sta.RenameTest) had already find the element ('xpath', '/html/body/div[3]/div/div[2]/div[3]/table/tbody/tr[4]/td[1]/label')
2019-07-29 21:52:46,335 - base.py:[42] - [INFO] - The page of test_01renamefiles (n_rename_sta.RenameTest) had already find the element ('xpath', '/html/body/div[3]/div/div[2]/div[3]/table/thead/tr/th[2]/div/span/a[1]')
2019-07-29 21:52:47,421 - base.py:[42] - [INFO] - The page of test_01renamefiles (n_rename_sta.RenameTest) had already find the element ('xpath', "//*[@id='fileList']/tr[4]/td[2]/form/input")
2019-07-29 21:52:48,791 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000013F350EA5C0> had already find the element ('xpath', "//*[@id='expand']")
2019-07-29 21:52:50,881 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000013F350EA5C0> had already find the element ('xpath', "//*[@id='expanddiv']/ul/li[2]/a")
2019-07-29 21:52:54,343 - base.py:[28] - [INFO] - _open is accessing address http:192.168.0.91 at line[46]
2019-07-29 21:52:54,343 - base.py:[32] - [INFO] - http:192.168.0.91 loading successed!
2019-07-29 21:52:54,367 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000013F350EA470> had already find the element ('xpath', "//*[@id='user']")
2019-07-29 21:52:54,429 - base.py:[64] - [INFO] - inputValue:[('xpath', "//*[@id='user']")] is receiveing value [admin]
2019-07-29 21:52:54,448 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000013F350EA470> had already find the element ('xpath', "//*[@id='password']")
2019-07-29 21:52:54,515 - base.py:[64] - [INFO] - inputValue:[('xpath', "//*[@id='password']")] is receiveing value [admin2003]
2019-07-29 21:52:54,532 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000013F350EA470> had already find the element ('xpath', "//*[@id='submit']")
2019-07-29 21:52:55,626 - base.py:[42] - [INFO] - The page of test_02renamefolders (n_rename_sta.RenameTest) had already find the element ('xpath', '/html/body/div[3]/div/div[2]/div[3]/table/tbody/tr[2]/td[1]/label')
2019-07-29 21:52:56,724 - base.py:[42] - [INFO] - The page of test_02renamefolders (n_rename_sta.RenameTest) had already find the element ('xpath', '/html/body/div[3]/div/div[2]/div[3]/table/thead/tr/th[2]/div/span/a[1]')
2019-07-29 21:52:57,800 - base.py:[42] - [INFO] - The page of test_02renamefolders (n_rename_sta.RenameTest) had already find the element ('xpath', "//*[@id='fileList']/tr[2]/td[2]/form/input")
2019-07-29 21:52:59,135 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000013F350EA470> had already find the element ('xpath', "//*[@id='expand']")
2019-07-29 21:53:01,222 - base.py:[42] - [INFO] - The page of <page_obj.LoginPage.login object at 0x0000013F350EA470> had already find the element ('xpath', "//*[@id='expanddiv']/ul/li[2]/a")
